name: Release

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Auto version and tag
        uses: entech-code/auto-version-tagging-action@fd3ec6c9309a0168e8f23782a1792564f3a6680e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          majorVersion: 0
          tagPrefix: "v"
